name = "NDSMC Modpack Lite"
author = "FnlTochka"
version = "1.0.0+lite.1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f78748c7e76d5a26cbfd07d9e5cb258d8f2be7e41060a9a746fefdeef13ad6d"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.19.4", "1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4"]
