name = "NDSMC Modpack Base"
author = "FnlTochka"
version = "1.0.0+base.1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1589729dea85a7c2bd11cc73773154e940446001e8b6652b9b3a23da2bb1cdc5"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.19.4", "1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4"]
